// @flow
// Automatically generated by Jenny. DO NOT EDIT!
import matchstick from 'matchstick'
import fetch from 'cross-fetch';
import url from 'url';


type Domain = {
    Available?: boolean,
  Name?: string,
  Whois?: string,
}


export default class NetClient {
  constructor(baseurl: string) {
    this.baseURL=baseurl
   }
  baseURL = ""

  async Whois( Name: string,) : Promise<Domain>  {
  let pathMaker = matchstick(this.baseURL+`/whois/{name}`, 'template');
  let path = pathMaker.stick({  name: Name, })
  let u = url.parse(path)
  let data : Domain  =  await fetch(path);
  return data
}

}
